-- Snowflake storage integration for Amazon S3

USE DATABASE NEWS_DB;
USE SCHEMA NEWS_SCHEMA;

CREATE OR REPLACE STORAGE INTEGRATION NEWS_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'YOUR_AWS_ROLE_ARN'
STORAGE_ALLOWED_LOCATIONS = (
    's3://news-data-aparna-2026/news/'
);

-- After creation, use DESC INTEGRATION to obtain
-- the Snowflake IAM user ARN and external ID.
DESC INTEGRATION NEWS_S3_INTEGRATION;
