-- Create database and schema
CREATE DATABASE IF NOT EXISTS NEWS_DB;

USE DATABASE NEWS_DB;

CREATE SCHEMA IF NOT EXISTS NEWS_SCHEMA;

USE SCHEMA NEWS_SCHEMA;

-- Final structured news table
CREATE OR REPLACE TABLE NEWS_DATA (
    SOURCE VARCHAR,
    AUTHOR VARCHAR,
    TITLE VARCHAR,
    DESCRIPTION VARCHAR,
    URL VARCHAR,
    PUBLISHED_AT TIMESTAMP_NTZ,
    CONTENT VARCHAR
);
